### ISSUE TITLE
Deno Deply not recognizing JSX

### ISSUE THREAD

**Issue by gutenfries** [gutenfries/gutenfries.deno.dev#7]
All files are being uploaded to Deno Deploy, however there is an issue somewhere, where deno does not recognize the JSX.

Errors from the server console:

```console
ReferenceError: h is not defined
    at Object.ErrorPage (file:///src/routes/_500.tsx:2:19)
    at https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1626
    at E (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1653)
    at E (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at q (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:316)
    at realRender (https://deno.land/x/fresh@1.1.1/src/server/render.ts:109:20)
    at Object.render (https://deno.land/x/fresh@1.1.1/src/server/render.ts:128:13)
```

The client-side page loads succesfully, with an HTTP 500 server error

**Comment by gutenfries** [comment]
# Closed 
with commit [c4256aaa0b2d60dec765b9883725c7679ac1e971](https://github.com/gutenfries/gutenfries.com/commit/c4256aaa0b2d60dec765b9883725c7679ac1e971)
## See comment 
> # [close issue](https://github.com/gutenfries/gutenfries.com/commit/c4256aaa0b2d60dec765b9883725c7679ac1e971#commitcomment-84201734) #7
> 
> JSX now works as expected. The issue was more than probably an immature version of [fresh](https://fresh.deno.dev)
> 
> production is now live @[gutenfries.deno.dev](https://gutenfries.deno.dev) 🥳🥳
